name: Pre-Merge Hook
on:
  pull_request:
    branches:
      - master
    types: [opened]

jobs:
  pre-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: |
          npm install
          
      - name: Install typoscripto
        run: |
          npm install -g typescript
          
      - name: build project               #
        run: |                            
          npm run build 
  
      - name: copy data to dist folder    #
        run: |                          
          npm run copy-files

      - name: Run test script
        run: |
          npm run test
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        if: ${{ failure() }}
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          # connection_url: 
          # Required mail server address if not connection_url:
          server_address: ${{secrets.MAIL_CONNECTION}}
          # Server port, default 25:
          server_port:  ${{secrets.MAIL_PORT}}
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: false #change to true in prod
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: You're fired 
          # Required recipients' addresses:
          to: you@me.com
          # Required sender full name (address can be skipped):
          from: Me, dio # <user@example.com>
          # Optional plain body:
          body: It works!! (but actually doesn't)
          # Optional HTML body read from file:
          # html_body: file://README.html
          # Optional carbon copy recipients:
          # cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          # reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          # in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          # convert_markdown: true
          # Optional attachments:
          # attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          # priority: low
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        if: ${{ success() }}
        with:
          server_address: ${{secrets.MAIL_CONNECTION}}
          server_port:  ${{secrets.MAIL_PORT}}
          secure: false #change to true in prod
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: You're not fired yet
          to: you@me.com
          from: Me, dio # <user@example.com>
          body: It works!! (but actually does)
          ignore_cert: true